name: floating_logger_boilerplate
description: "floating logger simple boilerplate api public by : https://fakestoreapi.com/"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  floating_logger: ^0.1.2
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
